[package]
name = "minimal-warp"
version = "0.1.0"
rust-version = "1.64"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.*", features = ["full"] }
warp = { version = "0.3.*" }